import type { Metadata } from 'next'
import './globals.css'
import MainHeader from './components/header/main-header'
import SideNavigation from './components/header/side-nav'
export const metadata: Metadata = {
  title: 'TMDB Movie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="px-8 bg-slate-200 inner">
        <MainHeader />
        <div className="grid grid-cols-8 gap-2">
          <SideNavigation />
          <main className="col-span-7">{children}</main>
        </div>
      </body>
    </html>
  )
}
