import type { Metadata } from 'next'
import './globals.css'
import MainHeader from './components/header/mainHeader'
import SideNavigation from './components/header/sideNav'

export const metadata: Metadata = {
  title: 'TMDB Movie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="px-8 inner">
        <MainHeader />
        <div className="grid grid-cols-8 gap-2">
          <SideNavigation />
          <main className="col-span-7 w-full mx-auto">{children}</main>
        </div>
        <footer className="flex items-center justify-center h-40 text-center">
          <span>OJ</span>
        </footer>
      </body>
    </html>
  )
}
